# Основные настройки
tg_channel: "" # название тг бота
tg_bot_token: "" # токен вашего тг бота
vk_token: "" # ваш токен в ВК приложении
vk_domain: "" # ваш домен в ВК приложении 
vk_group_id: "" # ваш id сообщества вк
tg_phone_number: "" # ваш номер телефона
api_id:   # ваш api id в приложении телеграмма
api_hash: "" # ваш api hash в приложении телеграмма
# Параметры парсинга
req_count: 10
time_to_sleep: 3

# Опции фильтрации контента
blacklist: ["ссылк", "купить", "заказать"]
whitelist: ["python", "javascript", "programming"]
skip_ads_posts: true
skip_reposts: true
skip_copyrighted_posts: true
skip_comments_with_links: true
author_comment_blacklist: ["https://", "t.me"]

# Опции публикации
publish_links_as_hyperlinks: false
default_signature: "Взято из: Телеграм (https://t.me/telegram)\n\n"
signature_format: "markdown"

# Опции для медиа
download_video: true
download_vk_clips: false

# Дополнительные опции
last_known_post_id: 0
single_start: false
