# Основные настройки
tg_channel: "@your_telegram_channel"  # Название канала
tg_bot_token: "your_bot_token"        # Токен бота
vk_token: "your_vk_token"            # Токен ВКонтакте
vk_domain: "your_vk_domain"          # Домен ВКонтакте

# Параметры парсинга
req_count: 10                       # Количество постов за раз
time_to_sleep: 3                    # Время ожидания между запросами
req_filter: ["posts", "comments"]   # Тип контента для парсинга (posts, comments)

# Опции фильтрации контента
blacklist: ["ссылк", "купить", "заказать"]      # Блэклист слов
whitelist: ["python", "javascript", "programming"] # Вайтлист слов
skip_ads_posts: true                  # Пропускать рекламные посты
skip_reposts: true                   # Пропускать репосты
skip_copyrighted_posts: true          # Пропускать защищённые авторским правом посты
skip_comments_with_links: true       # Пропускать комментарии с ссылками
author_comment_blacklist: ["https://", "t.me"]  # Блэклист ссылок в комментариях автора

# Опции публикации
publish_links_as_hyperlinks: false    # Публиковать ссылки как гиперссылки
default_signature: "Взято из: Телеграм (https://t.me/telegram)\n\n" # Подпись по умолчанию
signature_format: "markdown"         # Формат подписи (markdown, plain)

# Опции для медиа
download_video: true                 # Скачивать видео
download_vk_clips: false              # Скачивать ВК клипы

# Дополнительные опции
last_known_post_id: 0                 # ID последнего обработанного поста
single_start: false                   # Запустить парсинг только один раз
