tg_channel: "" # название тг бота
tg_bot_token: "" # токен вашего тг бота 
vk_token: "" # ваш токен ВК приложения 
vk_owner_id: -123456789  # замените на ID группы, добавьте знак минус перед ID
tg_phone_number: "" # номер телефона, зарегистрированный в тг
api_id: # ваш api_id после создания приложения в тг
api_hash: '' # ваш api_hash после создания приложения в тг

req_count: 10  
time_to_sleep: 300  
single_start: false  
skip_reposts: false  
skip_ads_posts: false  
skip_copyrighted_posts: false  
download_video: false  
default_signature: "Ваша подпись"  
signature_format: "markdown"  
publish_links_as_hyperlinks: true  
blacklist: ["плохое слово 1", "плохое слово 2"]  
whitelist: ["хорошее слово 1", "хорошее слово 2"]  
author_comment_blacklist: ["запрещенная ссылка 1", "запрещенная ссылка 2"]  
skip_comments_with_links: false  
